const state={view:"overview",connected:false,sessions:[],cron:[],analytics:null,sources:[{type:"OFFICIAL",title:"Hermes feature map",path:"../SOURCES/web/nousresearch/hermes-docs/extracted/feature-map.md",status:"verified"},{type:"CREATOR",title:"Komputer Mechanic Mission Control 3.0",path:"../SOURCES/web/komputer-mechanic/hermes-agent-corpus/source.md",status:"community"}]};
const app=document.querySelector("#app"),title=document.querySelector("#view-title");
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const card=(h,c="card")=>'<div class="'+c+'">'+h+"</div>";
function connection(){const c=Runtime.load();return card('<div class="card-head"><h2>Hermes backend</h2><span class="pill">'+(state.connected?"CONNECTED":"NOT CONNECTED")+"</span></div>"+'<div class="command"><input id="base-url" value="'+esc(c.baseUrl)+'" placeholder="http://127.0.0.1:8642"><input id="api-key" type="password" value="'+esc(c.apiKey)+'" placeholder="API key"><button onclick="connectRuntime()">Connect</button></div><div id="runtime-note" class="notice">'+(state.connected?"Native Hermes API responding.":"Enter the native Hermes API endpoint and key, then connect.")+"</div>")}
function overview(){const sessions=state.sessions||[],cron=state.cron||[];return '<div class="grid stats">'+card('<div class="stat-label">SESSIONS</div><div class="stat-value">'+sessions.length+'</div><div class="muted">native Hermes session API</div>')+card('<div class="stat-label">CRON JOBS</div><div class="stat-value">'+cron.length+'</div><div class="muted">native Hermes scheduler</div>')+card('<div class="stat-label">BACKEND</div><div class="stat-value">'+(state.connected?"LIVE":"OFFLINE")+'</div><div class="muted">no demo runtime state</div>')+card('<div class="stat-label">CONTROL LAYER</div><div class="stat-value">MC</div><div class="muted">Mission Control UI</div>')+'</div><div class="grid two" style="margin-top:14px">'+connection()+card('<div class="card-head"><h2>Recent sessions</h2><span class="pill">NATIVE</span></div>'+(sessions.length?sessions.slice(0,8).map(s=>'<div class="source-row"><div class="source-type">SESSION</div><div><div class="source-title">'+esc(s.title||s.id)+'</div><div class="source-url">'+esc(s.source||s.model||"Hermes")+'</div></div><span class="pill">'+esc(s.status||"stored")+'</span></div>').join(""):'<div class="notice">No sessions loaded.</div>')+'</div></div><div style="margin-top:14px">'+card('<div class="card-head"><h2>Mission layer</h2><span class="pill">NEXT BUILD</span></div><div class="notice">Missions, approval gates, fleet-wide activity and Agent City belong here. Native Hermes sessions, cron, logs and tools remain the backend truth.</div>')+'</div>'}
function agents(){return card('<div class="card-head"><h2>Fleet control</h2><span class="pill">PROFILE-AWARE</span></div><div class="notice">Agent profiles are not hard-coded here. This view will consume Hermes profile/session data once the fleet adapter is added.</div>')}
function missions(){return card('<div class="card-head"><h2>Missions</h2><span class="pill">CONTROL LAYER</span></div><div class="notice">Mission lifecycle: draft → plan → owner approval → execution → verification → report. Hermes remains responsible for actual agent execution.</div>')}
function sources(){return card('<div class="card-head"><h2>Research evidence</h2><span class="pill">PROVENANCE</span></div>'+state.sources.map(s=>'<div class="source-row"><div class="source-type">'+s.type+'</div><div><div class="source-title">'+esc(s.title)+'</div><div class="source-url">'+esc(s.path)+'</div></div><span class="pill">'+s.status+'</span></div>').join(""))}
function workflows(){return card('<div class="card-head"><h2>Mission Control architecture</h2><span class="pill">NO DUPLICATION</span></div>'+["Fleet cockpit: aggregate agents, activity and health","Mission lifecycle: plan and explicit approval before consequential work","Unified activity: delegation, tools, transitions, errors and completion","Operator controls: approve, stop, retry, assign/reassign","Files/docs and machine views over Hermes-native capabilities","Live updates over native event/session surfaces","Visual layer: Agent City / cockpit presentation"].map(x=>'<div class="source-row"><div class="source-type">MC</div><div class="source-title">'+esc(x)+'</div></div>').join(""))}
async function refreshRuntime(){try{const [s,c]=await Promise.all([Runtime.sessions(50),Runtime.cron()]);state.sessions=s.sessions||s||[];state.cron=c.jobs||c||[];state.connected=true}catch(e){state.connected=false}}
window.connectRuntime=async()=>{const baseUrl=document.querySelector("#base-url")?.value.trim(),apiKey=document.querySelector("#api-key")?.value.trim();Runtime.save({baseUrl,apiKey});await refreshRuntime();render()};
window.runCommand=async()=>{const input=document.querySelector("#cmd")?.value.trim();if(!input)return;const o=document.querySelector("#cmdout");try{o.textContent="Creating native Hermes session…";const created=await fetch(Runtime.load().baseUrl.replace(/\/$/,"")+"/api/sessions",{method:"POST",headers:{"Content-Type":"application/json",...(Runtime.load().apiKey?{Authorization:"Bearer "+Runtime.load().apiKey}:{})},body:JSON.stringify({title:"Mission Control"})});if(!created.ok)throw new Error("Session create failed: "+created.status);const s=await created.json();o.textContent="Session created: "+(s.id||s.session_id)+" | mission queued for native Hermes";}catch(e){o.textContent=e.message}}
async function render(){await refreshRuntime();const views={overview,agents,missions,sources,workflows};title.textContent=state.view[0].toUpperCase()+state.view.slice(1);app.innerHTML=views[state.view]();document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view))}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector("#refresh").onclick=render;render();
