const state={view:"overview",connected:false,sessions:[],cron:[],currentSession:null,messages:[],running:false,sources:[{type:"OFFICIAL",title:"Hermes API server",path:"https://hermes-agent.nousresearch.com/docs/user-guide/features/api-server",status:"verified"},{type:"CREATOR",title:"Komputer Mechanic Mission Control 3.0",path:"../SOURCES/web/komputer-mechanic/hermes-agent-corpus/source.md",status:"reference"}]};
const app=document.querySelector("#app"),title=document.querySelector("#view-title");
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const cfg=()=>Runtime.load();
async function api(path,options={}){return Runtime.request(path,options)}
function shell(body){return '<div class="grid two">'+body+"</div>"}
function connectCard(){const c=cfg();return '<div class="card"><div class="card-head"><h2>Hermes connection</h2><span class="pill">'+(state.connected?"CONNECTED":"OFFLINE")+'</span></div><div class="command"><input id="base-url" value="'+esc(c.baseUrl)+'" placeholder="http://127.0.0.1:8642"><input id="api-key" type="password" value="'+esc(c.apiKey)+'" placeholder="API key"><button onclick="connectRuntime()">Connect</button></div><div class="notice">Direct in-app chat uses Hermes session APIs. Telegram is not required.</div></div>'}
function overview(){return '<div class="grid stats">'+card('<div class="stat-label">SESSIONS</div><div class="stat-value">'+state.sessions.length+'</div><div class="muted">Hermes native</div>')+card('<div class="stat-label">CRON JOBS</div><div class="stat-value">'+state.cron.length+'</div><div class="muted">Hermes native</div>')+card('<div class="stat-label">CHAT</div><div class="stat-value">'+(state.currentSession?"LIVE":"READY")+'</div><div class="muted">in-app</div>')+card('<div class="stat-label">BACKEND</div><div class="stat-value">'+(state.connected?"LIVE":"OFFLINE")+'</div><div class="muted">127.0.0.1</div>')+'</div><div style="margin-top:14px">'+connectCard()+"</div>"+(state.connected?chatView():"")}
function chatView(){const rows=state.messages.map(m=>'<div class="source-row"><div class="source-type">'+esc(m.role||"message").toUpperCase()+'</div><div class="source-title" style="white-space:pre-wrap">'+esc(m.content||m.text||"")+'</div></div>').join("");return '<div class="card" style="margin-top:14px"><div class="card-head"><h2>Hermes conversation</h2><span class="pill">'+(state.currentSession?esc(state.currentSession.id):"NEW")+'</span></div><div class="command"><button onclick="newSession()">New chat</button></div><div style="max-height:420px;overflow:auto">'+(rows||'<div class="notice">Start a conversation. The response stays in this app and the session is persisted by Hermes.</div>')+'</div><div class="command"><input id="chat-input" placeholder="Message Hermes…" onkeydown="if(event.key===\'Enter\'&&!event.shiftKey){event.preventDefault();sendChat()}"><button id="send-chat" onclick="sendChat()">Send</button></div><div id="chat-status" class="notice">'+(state.running?"Hermes is working…":"")+'</div></div>'}
function card(h,c="card"){return '<div class="'+c+'">'+h+"</div>"}
async function loadSession(id){state.currentSession=await api("/api/sessions/"+encodeURIComponent(id));const data=await api("/api/sessions/"+encodeURIComponent(id)+"/messages");state.messages=data.messages||data||[]}
async function newSession(){state.currentSession=await api("/api/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:"Mission Control Chat"})});state.messages=[];render()}
async function sendChat(){const el=document.querySelector("#chat-input"),input=el?.value.trim();if(!input||state.running)return;el.value="";state.messages.push({role:"user",content:input});state.running=true;render();try{if(!state.currentSession)await newSession();const res=await fetch(cfg().baseUrl.replace(/\/$/,"")+"/api/sessions/"+encodeURIComponent(state.currentSession.id)+"/chat/stream",{method:"POST",headers:{"Content-Type":"application/json",...(cfg().apiKey?{Authorization:"Bearer "+cfg().apiKey}:{})},body:JSON.stringify({input})});if(!res.ok)throw new Error("Hermes chat failed: "+res.status);const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="",assistant="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parts=buffer.split("\n\n");buffer=parts.pop()||"";for(const part of parts){const line=part.split("\n").find(x=>x.startsWith("data:"));if(!line)continue;const raw=line.slice(5).trim();if(!raw||raw==="[DONE]")continue;try{const ev=JSON.parse(raw);if(ev.type==="assistant.delta")assistant+=ev.text||ev.delta||"";else if(ev.type==="assistant.completed")assistant=ev.text||ev.content||assistant;else if(ev.type==="tool.started")document.querySelector("#chat-status").textContent="Tool: "+(ev.name||ev.tool||"running");}catch{}}}state.messages.push({role:"assistant",content:assistant||"(Hermes completed without text output.)"});await loadSession(state.currentSession.id)}catch(e){state.messages.push({role:"error",content:e.message})}finally{state.running=false;render()}}
async function refreshRuntime(){try{const [s,c]=await Promise.all([api("/api/sessions?limit=50"),api("/api/cron/jobs")]);state.sessions=s.sessions||s||[];state.cron=c.jobs||c||[];state.connected=true}catch{state.connected=false}}
window.connectRuntime=async()=>{Runtime.save({baseUrl:document.querySelector("#base-url")?.value.trim(),apiKey:document.querySelector("#api-key")?.value.trim()});await refreshRuntime();render()};
window.newSession=newSession;window.sendChat=sendChat;
function agents(){return card('<div class="card-head"><h2>Fleet control</h2><span class="pill">HERMES NATIVE</span></div><div class="notice">Agent conversations now run directly through Hermes sessions. Fleet/profile aggregation is the next control-plane layer.</div>')}
function missions(){return card('<div class="card-head"><h2>Missions</h2><span class="pill">CONTROL LAYER</span></div><div class="notice">Mission lifecycle remains separate from direct chat: draft → plan → approval → execution → report.</div>')}
function sources(){return card('<div class="card-head"><h2>Sources</h2><span class="pill">PROVENANCE</span></div>'+state.sources.map(s=>'<div class="source-row"><div class="source-type">'+s.type+'</div><div><div class="source-title">'+esc(s.title)+'</div><div class="source-url">'+esc(s.path)+'</div></div><span class="pill">'+s.status+'</span></div>').join(""))}
function workflows(){return card('<div class="card-head"><h2>Mission Control</h2><span class="pill">LIVE CHAT FIRST</span></div><div class="notice">Direct conversation is implemented through Hermes native session APIs. Telegram remains optional.</div>')}
async function render(){await refreshRuntime();const views={overview,agents,missions,sources,workflows};title.textContent=state.view[0].toUpperCase()+state.view.slice(1);app.innerHTML=views[state.view]();document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view))}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector("#refresh").onclick=render;render();